# Generated by Django 4.2 on 2023-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_id', models.TextField(max_length=100)),
                ('sku', models.TextField(max_length=100)),
                ('ean', models.TextField(blank=True, max_length=100)),
                ('Estan', models.TextField(blank=True, max_length=100)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
    ]
