# Generated by Django 4.2 on 2023-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estan',
            name='bl_id',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estan',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
