# Generated by Django 4.2 on 2023-04-04 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estan', '0002_alter_estan_bl_id_alter_estan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='imp_excle',
            fields=[
                ('ex_id', models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='estan_import')),
            ],
        ),
    ]
